services:
  nodejs-mysql:
    image: mysql:8.0
    container_name: nodejs-mysql
    restart: always
    tty: true
    ports:
      - 7306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
  nodejs-dev:
    container_name: e-shop-nestjs
    restart: always
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 7300:3000
    volumes:
      - ../app:/var/applications/app
